import { captainArchetypes } from '../data/captainArchetypes.js';
import { ORIGIN_LORE, starterShips } from '../data/starterShips.js';

export default class NewGameUI {
  constructor({ rootEl, candidates, onStart }) { this.rootEl=rootEl; this.candidates=candidates; this.onStart=onStart; this.selectedCompanions=[]; this.selectedShipId=null; this.selectedArchetypeId=null; this.commandStyle='Measured'; }
  mount(){ this.rootEl.innerHTML=`<section class='panel'><h2>New Game Setup</h2><p class='subtext'>${ORIGIN_LORE.starterScenario}</p><div class='step'><h3>1. Create Captain</h3><input id='captain-name' placeholder='Captain name' /><div id='arch-cards' class='setup-grid'></div><select id='command-style'><option>Measured</option><option>Aggressive</option><option>Defensive</option><option>Pragmatic</option></select><p id='arch-preview' class='subtext'></p></div><div class='step'><h3>2. Choose Two Companions</h3><p id='companion-warning' class='warning'></p><div id='companion-cards' class='setup-grid'></div></div><div class='step'><h3>3. Choose Starter Ship</h3><div id='ship-cards' class='setup-grid'></div></div><button id='start-company'>Start Company</button><p id='setup-warning' class='warning'></p></section>`; this.bind(); this.render(); }
  bind(){ this.rootEl.querySelector('#command-style').addEventListener('change',(e)=>this.commandStyle=e.target.value); this.rootEl.querySelector('#start-company').addEventListener('click',()=>{ const captainName=this.rootEl.querySelector('#captain-name').value.trim(); if(!captainName||!this.selectedArchetypeId||this.selectedCompanions.length!==2||!this.selectedShipId){ this.rootEl.querySelector('#setup-warning').textContent='Complete all choices: name, archetype, two companions, and one ship.'; return; } this.onStart({captainName,captainArchetypeId:this.selectedArchetypeId,commandStyle:this.commandStyle,selectedCompanionIds:this.selectedCompanions,selectedStarterShipId:this.selectedShipId}); }); }
  render(){ const arch=this.rootEl.querySelector('#arch-cards'); arch.innerHTML=''; captainArchetypes.forEach((a)=>{ const b=document.createElement('button'); b.className=`setup-card ${this.selectedArchetypeId===a.id?'selected':''}`; b.innerHTML=`<strong>${a.name}</strong><p>${a.description}</p><p class='subtext'>Traits: ${a.traits.join(', ')}</p>`; b.onclick=()=>{this.selectedArchetypeId=a.id; this.rootEl.querySelector('#arch-preview').textContent=`${a.background} | Mods: ${JSON.stringify(a.attributeModifiers)}`; this.render();}; arch.appendChild(b);}); const cc=this.rootEl.querySelector('#companion-cards'); cc.innerHTML=''; this.candidates.forEach((c)=>{ const active=this.selectedCompanions.includes(c.id); const disabled=!active&&this.selectedCompanions.length>=2; const b=document.createElement('button'); b.disabled=disabled; b.className=`setup-card ${active?'selected':''}`; b.innerHTML=`<strong>${c.name}</strong><p>${c.species} • ${c.archetype}</p><p>${c.rolePreference} | $${c.wage}</p><p class='subtext'>${c.backstory}</p>`; b.onclick=()=>{ this.selectedCompanions=active?this.selectedCompanions.filter((id)=>id!==c.id):[...this.selectedCompanions,c.id]; this.render();}; cc.appendChild(b);}); this.rootEl.querySelector('#companion-warning').textContent=`Selected ${this.selectedCompanions.length}/2`; const sc=this.rootEl.querySelector('#ship-cards'); sc.innerHTML=''; starterShips.forEach((s)=>{ const d=Object.entries(s.compartments).filter(([,v])=>v.status!=='Operational').map(([k,v])=>`${k} ${v.status}`); const b=document.createElement('button'); b.className=`setup-card ${this.selectedShipId===s.id?'selected':''}`; b.innerHTML=`<strong>${s.name}</strong><p>${s.hullClass}</p><p>${s.role}</p><p>Crew ${s.minCrew}/${s.optimalCrew}/${s.maxCrew} • Fuel ${s.startingFuel}/${s.fuelCapacity} • Cargo ${s.cargoCapacity}</p><p>Officer slots: ${s.officerSlots}</p><p>Quirks: ${s.quirks.join(', ')}</p><p class='subtext'>Damaged: ${d.join(', ')}</p><p class='subtext'>Best fit: ${s.bestCareerFit}</p>`; b.onclick=()=>{this.selectedShipId=s.id; this.render();}; sc.appendChild(b);}); }
}
